### ISSUE TITLE
Installation error: Drupal 7 / CiviCRM 5.0.1

### ISSUE THREAD

**Issue by CharlesNepote** [veda-consulting/uk.co.vedaconsulting.gdpr#71]
Updating the DB at the end of the installation:

```
[Error: Upgrade uk.co.vedaconsulting.gdpr to revision 1201]

Exception: "API error: DB Constraint Violation - domain_id should possibly be marked as mandatory for Dashboard,create API. If so, please raise a bug report."

#0 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(265): CRM_Core_ManagedEntities->onApiError("Dashboard", "create", (Array:6), (Array:4))
#1 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(168): CRM_Core_ManagedEntities->updateExistingEntity(Object(CRM_Core_DAO_Managed), (Array:4))
#2 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(141): CRM_Core_ManagedEntities->reconcileEnabledModule(Object(CRM_Core_Module), (Array:3))
#3 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Upgrader.php(146): CRM_Core_ManagedEntities->reconcileEnabledModules()
#4 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Upgrader/Base.php(72): CRM_Gdpr_Upgrader->upgrade_1201()
#5 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Task.php(88): CRM_Gdpr_Upgrader_Base::_queueAdapter(Object(CRM_Queue_TaskContext), "upgrade_1201")
#6 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Runner.php(214): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
#7 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)
#8 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()
#9 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))
#10 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(275): CRM_Queue_Page_AJAX::runNext()
#11 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
#12 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#13 /var/www/xxxxxxx/root/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:4))
#14 /var/www/xxxxxxx/root/includes/menu.inc(527): civicrm_invoke("queue", "ajax", "runNext")
#15 /var/www/xxxxxxx/root/index.php(21): menu_execute_active_handler()
#16 {main}

[Error: Upgrade uk.co.vedaconsulting.gdpr to revision 1203]

Exception: "API error: DB Constraint Violation - domain_id should possibly be marked as mandatory for Dashboard,create API. If so, please raise a bug report."

#0 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(265): CRM_Core_ManagedEntities->onApiError("Dashboard", "create", (Array:6), (Array:4))
#1 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(168): CRM_Core_ManagedEntities->updateExistingEntity(Object(CRM_Core_DAO_Managed), (Array:4))
#2 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(141): CRM_Core_ManagedEntities->reconcileEnabledModule(Object(CRM_Core_Module), (Array:3))
#3 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Upgrader.php(174): CRM_Core_ManagedEntities->reconcileEnabledModules()
#4 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Upgrader/Base.php(72): CRM_Gdpr_Upgrader->upgrade_1203()
#5 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Task.php(88): CRM_Gdpr_Upgrader_Base::_queueAdapter(Object(CRM_Queue_TaskContext), "upgrade_1203")
#6 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Runner.php(214): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
#7 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)
#8 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()
#9 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))
#10 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(275): CRM_Queue_Page_AJAX::runNext()
#11 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
#12 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#13 /var/www/xxxxxxx/root/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:4))
#14 /var/www/xxxxxxx/root/includes/menu.inc(527): civicrm_invoke("queue", "ajax", "runNext")
#15 /var/www/xxxxxxx/root/index.php(21): menu_execute_active_handler()
#16 {main}

[Error: Upgrade uk.co.vedaconsulting.gdpr to revision 1204]

Exception: "A fatal error was triggered"

#0 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/BAO/CustomGroup.php(1848): CRM_Core_Error::fatal()
#1 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/BAO/CustomGroup.php(1860): CRM_Core_BAO_CustomGroup::mapTableName("ContributionPage")
#2 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(332): CRM_Core_BAO_CustomGroup::createTable(Object(CRM_Core_DAO_CustomGroup))
#3 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(80): CRM_Utils_Migrate_Import->customGroups(Object(SimpleXMLElement), (Array:2))
#4 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Utils/Migrate/Import.php(58): CRM_Utils_Migrate_Import->runXmlElement(Object(SimpleXMLElement))
#5 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Upgrader/Base.php(102): CRM_Utils_Migrate_Import->run("/var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gd...")
#6 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Upgrader/Base.php(90): CRM_Gdpr_Upgrader_Base::executeCustomDataFileByAbsPath("/var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gd...")
#7 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Upgrader.php(187): CRM_Gdpr_Upgrader_Base->executeCustomDataFile("xml/CustomGroupData.xml")
#8 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/Upgrader/Base.php(72): CRM_Gdpr_Upgrader->upgrade_1204()
#9 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Task.php(88): CRM_Gdpr_Upgrader_Base::_queueAdapter(Object(CRM_Queue_TaskContext), "upgrade_1204")
#10 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Runner.php(214): CRM_Queue_Task->run(Object(CRM_Queue_TaskContext))
#11 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(52): CRM_Queue_Runner->runNext(TRUE)
#12 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/ErrorPolicy.php(106): CRM_Queue_Page_AJAX::{closure}()
#13 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Queue/Page/AJAX.php(54): CRM_Queue_ErrorPolicy->call(Object(Closure))
#14 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(275): CRM_Queue_Page_AJAX::runNext()
#15 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))
#16 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#17 /var/www/xxxxxxx/root/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:4))
#18 /var/www/xxxxxxx/root/includes/menu.inc(527): civicrm_invoke("queue", "ajax", "runNext")
#19 /var/www/xxxxxxx/root/index.php(21): menu_execute_active_handler()
#20 {main}
```
Then when I open a contact, it fails with this message:
```
CiviCRM_API3_Exception: "'SLA Acceptance' is not a valid option for field activity_type_id"

#0 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/CRM/Gdpr/SLA/Utils.php(112): civicrm_api3("Activity", "get", (Array:5))
#1 /var/www/xxxxxxx/root/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr-2.3/gdpr.php(476): CRM_Gdpr_SLA_Utils::getContactLastAcceptance("31431")
#2 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Utils/Hook.php(270): gdpr_civicrm_pageRun(Object(CRM_Contact_Page_View_Summary))
#3 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(84): CRM_Utils_Hook->runHooks((Array:47), "civicrm_pageRun", 1, Object(CRM_Contact_Page_View_Summary), NULL, NULL, NULL, NULL, NULL)
#4 /var/www/xxxxxxx/root/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(86): CRM_Utils_Hook_DrupalBase->invokeViaUF(1, Object(CRM_Contact_Page_View_Summary), NULL, NULL, NULL, NULL, NULL, "civicrm_pageRun")
#5 [internal function](): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_pageRun", Object(Civi\Core\CiviEventDispatcher))
#6 /var/www/xxxxxxx/root/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func((Array:2), Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_pageRun", Object(Civi\Core\CiviEventDispatcher))
#7 /var/www/xxxxxxx/root/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_pageRun", Object(Civi\Core\Event\GenericHookEvent))
#8 /var/www/xxxxxxx/root/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_pageRun", Object(Civi\Core\Event\GenericHookEvent))
#9 /var/www/xxxxxxx/root/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch("hook_civicrm_pageRun", Object(Civi\Core\Event\GenericHookEvent))
#10 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Utils/Hook.php(164): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_pageRun", Object(Civi\Core\Event\GenericHookEvent))
#11 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Utils/Hook.php(795): CRM_Utils_Hook->invoke((Array:1), Object(CRM_Contact_Page_View_Summary), NULL, NULL, NULL, NULL, NULL, "civicrm_pageRun")
#12 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Page.php(177): CRM_Utils_Hook::pageRun(Object(CRM_Contact_Page_View_Summary))
#13 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Contact/Page/View/Summary.php(96): CRM_Core_Page->run()
#14 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Contact_Page_View_Summary->run((Array:3), NULL)
#15 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:14))
#16 /var/www/xxxxxxx/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#17 /var/www/xxxxxxx/root/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#18 /var/www/xxxxxxx/root/includes/menu.inc(527): civicrm_invoke("contact", "view")
#19 /var/www/xxxxxxx/root/index.php(21): menu_execute_active_handler()
#20 {main}
```
I had to disable the extension to let it work again.

**Comment by CharlesNepote** [comment]
Let me know if I can help in any way.

**Comment by cmolava** [comment]
Hi, would you be able to try running a core database upgrade at http://YOURSITE/civicrm/upgrade. (If there are no upgrades pending it may throw an error, but this isn't anything to worry about). Then go back to the extensions page and see if there are any updgrades available for other extensions you have installed. If there are database upgrades, perform those and then uninstall and reinstall the gdpr extension.

**Comment by veda-consulting** [comment]
@CharlesNepote FYI if you could let us know we can take a further look

**Comment by nalonsopress** [comment]
The errors in your error log don't exactly match the issue I was having, but it is very similar. The first thing I did was disable and reenable the CiviContribute component. That created a table that wasn't previously there. The second thing I did was run this code on it's own 

$import = new CRM_Utils_Migrate_Import();
$import->run('/var/www/html/wp-content/uploads/civicrm/php/CustomData_v1.xml');

That created the necessary table for the SLA Acceptance. Keep in mind also, this is using a WordPress install.

**Comment by veda-consulting** [comment]
closing for now, can reopen if further help is required

**Comment by CharlesNepote** [comment]
The extension is now working fine. It was installed by @tttp so I don't know what he did to make it work. Xavier?

**Comment by hanswundersam** [comment]
Dear @veda-consulting, we have the exact same problem with the GDPR extension. As soon as it's enabled, every access attempt to any contacts in our DB throws a "'SLA Acceptance' is not a valid option for field activity_type_id" error. We run CiviCRM 5.3.0 and GDPR extension version 2.6 with Wordpress.

I tried deactivating and reactivating the CiviContribute component as per @nalonsopress instructions but am not sure how to "run this code on it's own". If this step is known to work, could you please give me a hint as to how to execute it?

Thank you!
